DROP DATABASE IF EXISTS STUDY_ORGANIZER;
CREATE DATABASE STUDY_ORGANIZER;
USE STUDY_ORGANIZER;

CREATE TABLE Users (
    U_ID INT PRIMARY KEY AUTO_INCREMENT,
    U_username VARCHAR(255) NOT NULL UNIQUE,
    U_password VARCHAR(255) NOT NULL,
    U_auth_key VARCHAR(255) NOT NULL,
    U_role VARCHAR(255) NOT NULL
);

CREATE TABLE Teachers (
    T_ID INT PRIMARY KEY AUTO_INCREMENT,
    T_name VARCHAR(255) NOT NULL,
    T_is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE Subjects (
    S_ID INT PRIMARY KEY AUTO_INCREMENT,
    S_name VARCHAR(255) NOT NULL UNIQUE,
    S_T_ID INT NOT NULL,
    FOREIGN KEY (S_T_ID) REFERENCES Teachers(T_ID)
);

CREATE TABLE Homework (
    H_ID INT PRIMARY KEY AUTO_INCREMENT,
    H_title VARCHAR(255) NOT NULL,
    H_description TEXT,
    H_due_date DATE NOT NULL,
    H_is_done BOOLEAN NOT NULL DEFAULT FALSE,
    H_S_ID INT NOT NULL,
    H_U_ID INT NOT NULL,
    FOREIGN KEY (H_S_ID) REFERENCES Subjects(S_ID),
    FOREIGN KEY (H_U_ID) REFERENCES Users(U_ID)
);
